### ISSUE TITLE
rest incompleto

### ISSUE THREAD

**Issue by adrianmeca** [francoo27/JavaTPI#2]
Falta al menos un http method en cada uno

https://github.com/francoo27/JavaTPI/blob/9e39829595e8fd89db23fcb546bafc421c3b2096/BE/src/controller/ClasificacionServlet.java#L21

https://github.com/francoo27/JavaTPI/blob/9e39829595e8fd89db23fcb546bafc421c3b2096/BE/src/controller/ClasificacionListServlet.java#L35

**Comment by francoo27** [comment]
Se partio la entidad en 2 servlet
